---
- name: Install dependencies
  ansible.builtin.include_tasks: python.yml
  when: ansible_distribution != 'NixOS'

- name: Verify installation
  ansible.builtin.include_tasks:
    apply:
      tags: cogni-ai-agent-verify
    file: verify.yml
  tags: cogni-ai-agent-verify
